### ISSUE TITLE
Doesn't work on mac

### ISSUE THREAD

**Issue by spuder** [ValeriyKr/sfb#3]
```
 ./sfb.sh full
/usr/bin/sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Your 'sed' implementation isn't compatible with GNU sed well.
```

Not sure how hard that would be to fix. Maybe put a warning in the readme for osx users

**Comment by ValeriyKr** [comment]
I heard about this problem. As i know, OS X doesn't have GNU sed by default, there is BSD sed in there. Old BSD sed.

gsed's installing is described [here](https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/). I didn't try this, 'cos i don't have mac. But it has to work, as i know.

**Comment by samdunne** [comment]
`brew install gnu-sed && export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"`

Should fix your problem
